//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.cars = new HashSet<car>();
        }
    
        public int branch_id { get; set; }
        public int is_active { get; set; }
        public string branch_name { get; set; }
        public int city_id { get; set; }
        public decimal location_latitude { get; set; }
        public decimal location_longitude { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<car> cars { get; set; }
    }
}
