//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public car()
        {
            this.diaries = new HashSet<diary>();
        }
    
        public int car_id { get; set; }
        public int is_active { get; set; }
        public int car_number { get; set; }
        public int car_model_id { get; set; }
        public int mileage { get; set; }
        public string photo { get; set; }
        public bool available_for_rent { get; set; }
        public bool rentable { get; set; }
        public int owner_branch { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual car_models car_models { get; set; }
        public virtual ICollection<diary> diaries { get; set; }
    }
}
