//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_models
    {
        public car_models()
        {
            this.cars = new HashSet<car>();
        }
    
        public int car_model_id { get; set; }
        public int is_active { get; set; }
        public string model_name { get; set; }
        public int manufacturer_id { get; set; }
        public int transmission_id { get; set; }
        public int manufacture_year { get; set; }
        public decimal daily_rate { get; set; }
        public decimal day_late_rate { get; set; }
        public string remarks { get; set; }
    
        public virtual manufacturer manufacturer { get; set; }
        public virtual ICollection<car> cars { get; set; }
        public virtual transmission_types transmission_types { get; set; }
    }
}
