//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.branches = new HashSet<branch>();
        }
    
        public int city_id { get; set; }
        public int country_id { get; set; }
        public string city_name { get; set; }
    
        public virtual ICollection<branch> branches { get; set; }
        public virtual country country { get; set; }
    }
}
